// vue-ts/src/components/Header.vue
<template>
  <header v-if="!isErrorPage" class="px-4 py-4 max-w-2xl mx-auto sm:px-0">
    <Modal :open="showModal" :onClose="() => setShowModal(false)">
      <AddTodoForm :onSuccess="handleAddSuccess" />
    </Modal>
    <SuccessModal :open="showSuccess" />
    <nav>
      <div v-if="isHome">
        <button type="button" class="sm:hidden cursor-pointer" @click="setIsMenuOpen(!isMenuOpen)">
          <MdMenu :size="32" />
        </button>
        <ul
          :class="`sm:flex sm:justify-center sm:items-center ${
            isMenuOpen ? 'grid gap-5 bg-white p-4 rounded-md shadow-md' : 'hidden'
          }`"
        >
          <li>
            <RouterLink class="nav-link" to="/todos"> Todos </RouterLink>
          </li>
          <li>
            <RouterLink class="nav-link" to="/test-error"> Test Error Boundary </RouterLink>
          </li>
          <li>
            <button type="button" class="nav-btn w-full mt-7 sm:mt-0" @click="setShowModal(true)">
              Add Todo
            </button>
          </li>
        </ul>
      </div>

      <div v-if="!isHome">
        <ul class="flex justify-between items-center">
          <li>
            <RouterLink to="/">
              <span class="sr-only">Home</span>
              <LuHouse :size="32" />
            </RouterLink>
          </li>
          <li v-if="!isErrorPage">
            <button type="button" class="nav-btn" @click="setShowModal(true)">Add Todo</button>
          </li>
        </ul>
      </div>
    </nav>
  </header>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { LuHouse } from 'react-icons/lu'
import { MdMenu } from 'react-icons/md'
import Modal from './Modal.vue'
import AddTodoForm from './AddTodoForm.vue'
import SuccessModal from './SuccessModal.vue'

const route = useRoute()
const router = useRouter()
const path = computed(() => route.path)

const isHome = computed(() => path.value === '/')
const isErrorPage = computed(() => path.value === '/test-error')

const showModal = ref(false)
const showSuccess = ref(false)
const isMenuOpen = ref(false)

const setShowModal = (value: boolean) => {
  showModal.value = value
}

const setIsMenuOpen = (value: boolean) => {
  isMenuOpen.value = value
}

const handleAddSuccess = () => {
  setShowModal(false)
  showSuccess.value = true
  setTimeout(() => (showSuccess.value = false), 1000)
  if (path.value !== '/todos') router.push('/todos')
}
</script>

// next-ts/components/Header.tsx
'use client';

import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { useState } from 'react';
import { LuHouse } from 'react-icons/lu';
import Modal from '@/components/Modal';
import AddTodoForm from '@/components/AddTodoForm';
import SuccessModal from '@/components/SuccessModal';
import { MdMenu } from 'react-icons/md';

const Header = () => {
	const path = usePathname();
	const isHome = path === '/';
	const isErrorPage = path === '/test-error';
	const router = useRouter();

	const [showModal, setShowModal] = useState(false);
	const [showSuccess, setShowSuccess] = useState(false);
	const [isMenuOpen, setIsMenuOpen] = useState(false);

	const handleAddSuccess = () => {
		setShowModal(false);
		setShowSuccess(true);
		setTimeout(() => setShowSuccess(false), 1000);
		if (path !== '/todos') router.push('/todos');
	};

	return (
		<header className='px-8 py-4 max-w-5xl mx-auto'>
			<Modal open={showModal} onClose={() => setShowModal(false)}>
				<AddTodoForm onSuccess={handleAddSuccess} />
			</Modal>
			<SuccessModal open={showSuccess} />
			<nav>
				{isHome && (
					<>
						<button
							type='button'
							className='sm:hidden cursor-pointer'
							onClick={() => setIsMenuOpen(!isMenuOpen)}
						>
							<MdMenu size={32} />
						</button>
						<ul
							className={`sm:flex sm:justify-center sm:items-center ${
								isMenuOpen
									? 'grid gap-5 bg-white p-4 rounded-md shadow-md'
									: 'hidden'
							}`}
						>
							<li>
								<Link className='nav-link' href='/todos'>
									Todos
								</Link>
							</li>
							<li>
								<Link className='nav-link' href='/test-error'>
									Test Error Boundary
								</Link>
							</li>
							<li>
								<button
									type='button'
									className='nav-btn w-full mt-7 sm:mt-0'
									onClick={() => setShowModal(true)}
								>
									Add Todo
								</button>
							</li>
						</ul>
					</>
				)}

				{!isHome && (
					<ul className='flex justify-between items-center'>
						<li>
							<Link href='/'>
								<span className='sr-only'>Home</span>
								<LuHouse size={32} />
							</Link>
						</li>
						{!isErrorPage && (
							<li>
								<button
									type='button'
									className='nav-btn'
									onClick={() => setShowModal(true)}
								>
									Add Todo
								</button>
							</li>
						)}
					</ul>
				)}
			</nav>
		</header>
	);
};
export default Header;
