// next-ts/components/todo/TodoList.tsx
import { ITodo } from '@/app/types';
import TodoItem from './TodoItem';

type List = {
	todos: ITodo[];
};

const TodoList: React.FC<List> = ({ todos }) => {
	return (
		<div className='my-0 mx-auto'>
			{todos.map((todo) => (
				<TodoItem key={todo.id} todo={todo} />
			))}
		</div>
	);
};

export default TodoList;

// vue-ts/src/components/todo/TodoList.vue
<template>
  <div class="my-0 mx-auto">
    <TodoItem v-for="todo in todos" :key="todo.id" :todo="todo" />
  </div>
</template>

<script setup lang="ts">
import TodoItem from './TodoItem.vue'
import type { ITodo } from '../../types/index'

interface Props {
  todos: ITodo[]
}

defineProps<Props>()
</script>
