// vue-ts/src/components/NotFound.vue
<template>
  <div
    class="text-center grid place-content-center py-15 absolute h-screen w-screen bg-black top-0 left-0"
  >
    <div>
      <h1 class="text-5xl text-filter-blue mb-0">404</h1>
      <h2 class="text-white/60 mt-2">Page Not Found</h2>
      <p class="text-white/60 mt-7.5">Sorry, the page you are looking for does not exist.</p>
      <RouterLink
        to="/"
        class="inline-block py-2.5 px-6 bg-filter-blue mt-25 text-white rounded-sm font-medium"
      >
        Go Home
      </RouterLink>
    </div>
  </div>
</template>

<script setup lang="ts">
import { RouterLink } from 'vue-router'
</script>

// react-js/src/pages/NotFound.jsx
import React from 'react';
import { Link } from 'react-router-dom';

const NotFound = () => {
  return (
    <div style={{ textAlign: 'center', padding: '60px 20px' }}>
      <h1 style={{ fontSize: '4rem', color: '#1677ff', marginBottom: 0 }}>404</h1>
      <h2 style={{ color: '#333', marginTop: 0 }}>Page Not Found</h2>
      <p style={{ color: '#666', marginBottom: 30 }}>
        Sorry, the page you are looking for does not exist.
      </p>
      <Link
        to="/"
        style={{
          display: 'inline-block',
          padding: '10px 24px',
          background: '#1677ff',
          color: 'white',
          borderRadius: 4,
          textDecoration: 'none',
          fontWeight: 500,
        }}
      >
        Go Home
      </Link>
    </div>
  );
};

export default NotFound;
