// src/components/AddTodoForm.jsx
import { useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';

const createTodo = async (newTodo) => {
  const res = await fetch('https://dummyjson.com/todos/add', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(newTodo),
  });
  if (!res.ok) throw new Error('Failed to add todo');
  return res.json();
};

const AddTodoForm = ({ onSuccess }) => {
  const [todoText, setTodoText] = useState('');
  const queryClient = useQueryClient();

  const mutation = useMutation({
    mutationFn: createTodo,
    onSuccess: () => {
      queryClient.invalidateQueries(['todos']);
      if (onSuccess) onSuccess();
    },
  });

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!todoText.trim()) return;
    const newTodo = {
      todo: todoText,
      completed: false,
      userId: 1,
    };
    mutation.mutate(newTodo);
    setTodoText('');
  };

  return (
    <div style={{ minWidth: 300 }}>
      <h2>Add New Todo</h2>
      <form onSubmit={handleSubmit} style={{ display: 'flex', gap: 8 }}>
        <input
          type="text"
          placeholder="Enter todo"
          value={todoText}
          onChange={(e) => setTodoText(e.target.value)}
          style={{ flex: 1, padding: 8, borderRadius: 4, border: '1px solid #d9d9d9' }}
        />
        <button type="submit" disabled={mutation.isPending || !todoText.trim()} style={{ padding: '8px 16px', borderRadius: 4, background: '#1677ff', color: 'white', border: 'none', cursor: mutation.isPending ? 'not-allowed' : 'pointer' }}>
          {mutation.isPending ? 'Adding...' : 'Add'}
        </button>
      </form>
      {mutation.isError && <p style={{ color: '#ff4d4f', marginTop: 16 }}>Error: {mutation.error.message}</p>}
    </div>
  );
};

export default AddTodoForm;

// vue-ts/src/components/AddTodoForm.vue
<template>
  <div>
    <h2 class="text-2xl font-semibold">Add New Todo</h2>
    <form @submit.prevent="handleSubmit" class="grid gap-5 mt-9">
      <input
        type="text"
        placeholder="Enter todo"
        v-model="todoText"
        class="p-2 rounded-sm border border-gray-300 block w-full"
      />
      <button
        type="submit"
        :disabled="isPending || !todoText.trim()"
        :class="`py-2 px-4 rounded-sm w-full text-white bg-page-green ${
          isPending ? 'cursor-not-allowed' : 'cursor-pointer'
        }`"
      >
        {{ isPending ? 'Adding todo...' : 'Add' }}
      </button>
    </form>
    <p v-if="isError" class="mt-4 text-red-500">Error: {{ error?.message }}</p>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useMutation, useQueryClient } from '@tanstack/vue-query'
import type { ITodo } from '../types/index'

interface Props {
  onSuccess: () => void
}

const props = defineProps<Props>()

const todoText = ref('')
const queryClient = useQueryClient()

const createTodo = async (newTodo: ITodo) => {
  const res = await fetch('https://dummyjson.com/todos/add', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(newTodo),
  })
  if (!res.ok) throw new Error('Failed to add todo')
  return res.json()
}

const { mutate, isPending, isError, error } = useMutation({
  mutationFn: createTodo,
  onSuccess: () => {
    queryClient.invalidateQueries({ queryKey: ['todos'] })
    if (props.onSuccess) props.onSuccess()
  },
})

const handleSubmit = () => {
  if (!todoText.value.trim()) return
  const newTodo = {
    todo: todoText.value,
    completed: false,
    userId: Math.floor(Math.random() * 100) + 100,
    id: Math.floor(Math.random() * 100) + 1,
  }
  mutate(newTodo)
  todoText.value = ''
}
</script>
