// vue-ts/src/components/ErrorBoundary.vue
<template>
  <div v-if="hasError" class="text-center h-screen grid place-content-center">
    <div class="w-full">
      <h2 class="text-lg">Something went wrong globally.</h2>
      <pre class="text-red-500 text-lg mt-4">
				{{ error?.toString() }}
			</pre
      >

      <div class="w-full flex gap-6 mt-45 justify-center">
        <RouterLink to="/" class="back-link justify-between" @click="resetError">
          <IoChevronBack /> Back to Home
        </RouterLink>
        <button @click="resetError" class="cursor-pointer back-link">Try again</button>
      </div>
    </div>
  </div>
  <slot v-else />
</template>

<script setup lang="ts">
import { ref, onErrorCaptured } from 'vue'
import { RouterLink } from 'vue-router'
import { IoChevronBack } from 'react-icons/io5'

const hasError = ref(false)
const error = ref<Error | null>(null)

const resetError = () => {
  hasError.value = false
  error.value = null
}

onErrorCaptured((err) => {
  hasError.value = true
  error.value = err
  return false
})
</script>

// react-js/src/components/ErrorBoundary.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import { IoChevronBack } from 'react-icons/io5';

class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false, error: null };
  }

  static getDerivedStateFromError(error) {
    return { hasError: true, error };
  }

  componentDidCatch(error, errorInfo) {
    console.error('ErrorBoundary caught an error:', error, errorInfo);
  }

  resetError = () => {
    this.setState({ hasError: false, error: null });
  };

  render() {
    if (this.state.hasError) {
      return (
        <div style={{ padding: '50px 40px', textAlign: 'center' }}>
          <Link to="/" className="back-link" onClick={this.resetError}>
            <IoChevronBack /> Back to Home
          </Link>
          <h2 style={{ marginTop: 200 }}>Something went wrong.</h2>
          <pre style={{ color: 'red' }}>{this.state.error?.toString()}</pre>
        </div>
      );
    }
    return this.props.children;
  }
}

export default ErrorBoundary;
